"""otp request ip

Revision ID: 1bcb00ce0bbf
Revises: b48f60b2bfef
Create Date: 2026-09-30 13:20:32.112647

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1bcb00ce0bbf'
down_revision = 'b48f60b2bfef'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('request_ip', postgresql.INET(), nullable=True))
        batch_op.create_index('ix_otp_codes_request_ip_created_at', ['request_ip', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_codes_request_ip_created_at')
        batch_op.drop_column('request_ip')

    # ### end Alembic commands ###
