"""Pregnancy due-date corrections, and audit events for raised alerts and removed documents.

Revision ID: 32eb077dac4a
Revises: f52a06369cf8
Create Date: 2026-10-01 09:50:50.606139

"""
from alembic import op
import sqlalchemy as sa


# Audit event types are stored as VARCHAR with a CHECK constraint; listed here so this
# migration keeps meaning the same thing if the enum changes later.
OLD_AUDIT_EVENTS = (
    "profile_created", "record_viewed", "record_updated", "access_denied", "login_succeeded",
    "login_failed", "document_uploaded", "approval_granted", "approval_revoked",
    "record_created", "staff_account_created", "staff_account_updated", "midwife_chosen",
    "alert_seen", "partner_link_created", "partner_link_revoked", "partner_link_viewed",
)
NEW_AUDIT_EVENTS = OLD_AUDIT_EVENTS + ("alert_raised", "document_deleted")


def _audit_event_check(values) -> None:
    op.drop_constraint(op.f("ck_audit_logs_event_type_valid"), "audit_logs", type_="check")
    allowed = ", ".join(f"'{v}'" for v in values)
    op.create_check_constraint(
        op.f("ck_audit_logs_event_type_valid"), "audit_logs", f"event_type IN ({allowed})"
    )


# revision identifiers, used by Alembic.
revision = '32eb077dac4a'
down_revision = 'f52a06369cf8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.add_column(sa.Column('due_date_corrected_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('due_date_corrected_by_id', sa.UUID(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_pregnancies_due_date_corrected_by_id_users'), 'users', ['due_date_corrected_by_id'], ['id'])

    # ### end Alembic commands ###
    _audit_event_check(NEW_AUDIT_EVENTS)


def downgrade():
    # Fails if the log already holds the new event types: audit rows are never deleted.
    _audit_event_check(OLD_AUDIT_EVENTS)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_pregnancies_due_date_corrected_by_id_users'), type_='foreignkey')
        batch_op.drop_column('due_date_corrected_by_id')
        batch_op.drop_column('due_date_corrected_at')

    # ### end Alembic commands ###
