"""phase 1 data model

Revision ID: b48f60b2bfef
Revises: 
Create Date: 2026-09-28 06:24:06.755014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'b48f60b2bfef'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_logs',
    sa.Column('id', sa.BigInteger(), sa.Identity(always=False), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=True),
    sa.Column('patient_id', sa.UUID(), nullable=True),
    sa.Column('event_type', sa.Enum('profile_created', 'record_viewed', 'record_updated', 'access_denied', 'login_succeeded', 'login_failed', 'document_uploaded', 'approval_granted', 'approval_revoked', name='auditeventtype', native_enum=False, length=40), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=True),
    sa.Column('resource_id', sa.String(length=64), nullable=True),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('details', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('profile_created', 'record_viewed', 'record_updated', 'access_denied', 'login_succeeded', 'login_failed', 'document_uploaded', 'approval_granted', 'approval_revoked')", name=op.f('ck_audit_logs_event_type_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_logs_actor_created_at', ['actor_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_event_type'), ['event_type'], unique=False)
        batch_op.create_index('ix_audit_logs_patient_created_at', ['patient_id', 'created_at'], unique=False)

    op.create_table('otp_codes',
    sa.Column('mobile', sa.String(length=16), nullable=False),
    sa.Column('code_hash', sa.String(length=255), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('attempts', sa.SmallInteger(), server_default='0', nullable=False),
    sa.Column('consumed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('attempts >= 0', name=op.f('ck_otp_codes_attempts_non_negative')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_otp_codes'))
    )
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.create_index('ix_otp_codes_mobile_created_at', ['mobile', 'created_at'], unique=False)

    op.create_table('users',
    sa.Column('mobile', sa.String(length=16), nullable=False),
    sa.Column('role', sa.Enum('user', 'doctor', 'midwife', 'admin', name='userrole', native_enum=False, length=40), server_default='user', nullable=False),
    sa.Column('is_active', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('mobile_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mobile ~ '^\\+[1-9][0-9]{7,14}$'", name=op.f('ck_users_mobile_e164')),
    sa.CheckConstraint("role IN ('user', 'doctor', 'midwife', 'admin')", name=op.f('ck_users_role_valid')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('mobile', name=op.f('uq_users_mobile'))
    )
    op.create_table('care_approvals',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('approved_by_id', sa.UUID(), nullable=False),
    sa.Column('scope', sa.Enum('pregnancy_plan', 'rehabilitation_plan', name='approvalscope', native_enum=False, length=40), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("scope IN ('pregnancy_plan', 'rehabilitation_plan')", name=op.f('ck_care_approvals_scope_valid')),
    sa.ForeignKeyConstraint(['approved_by_id'], ['users.id'], name=op.f('fk_care_approvals_approved_by_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_care_approvals_patient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['revoked_by_id'], ['users.id'], name=op.f('fk_care_approvals_revoked_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_approvals'))
    )
    with op.batch_alter_table('care_approvals', schema=None) as batch_op:
        batch_op.create_index('uq_care_approvals_one_active_per_scope', ['patient_id', 'scope'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))

    op.create_table('fitness_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('goal', sa.Enum('weight_loss', 'muscle_gain', 'general_fitness', 'other', name='fitnessgoal', native_enum=False, length=40), nullable=False),
    sa.Column('goal_note', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("goal IN ('weight_loss', 'muscle_gain', 'general_fitness', 'other')", name=op.f('ck_fitness_profiles_goal_valid')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_fitness_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_fitness_profiles'))
    )
    op.create_table('medical_histories',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('previous_children_count', sa.SmallInteger(), nullable=True),
    sa.Column('miscarriage_count', sa.SmallInteger(), nullable=True),
    sa.Column('has_diabetes', sa.Boolean(), nullable=True),
    sa.Column('has_hypertension', sa.Boolean(), nullable=True),
    sa.Column('has_nutrient_deficiency', sa.Boolean(), nullable=True),
    sa.Column('nutrient_deficiency_details', sa.Text(), nullable=True),
    sa.Column('has_thyroid_disorder', sa.Boolean(), nullable=True),
    sa.Column('has_breast_cyst', sa.Boolean(), nullable=True),
    sa.Column('has_ovarian_cyst_pcos', sa.Boolean(), nullable=True),
    sa.Column('underlying_conditions', sa.Text(), nullable=True),
    sa.Column('has_previous_surgery', sa.Boolean(), nullable=True),
    sa.Column('previous_surgery_details', sa.Text(), nullable=True),
    sa.Column('has_anesthesia_history', sa.Boolean(), nullable=True),
    sa.Column('current_medications', sa.Text(), nullable=True),
    sa.Column('has_dental_infection', sa.Boolean(), nullable=True),
    sa.Column('dental_notes', sa.Text(), nullable=True),
    sa.Column('has_hiv', sa.Boolean(), nullable=True),
    sa.Column('has_hepatitis_b', sa.Boolean(), nullable=True),
    sa.Column('has_hepatitis_c', sa.Boolean(), nullable=True),
    sa.Column('other_infectious_diseases', sa.Text(), nullable=True),
    sa.Column('spouse_has_diabetes', sa.Boolean(), nullable=True),
    sa.Column('spouse_has_varicocele', sa.Boolean(), nullable=True),
    sa.Column('spouse_has_genetic_disorder', sa.Boolean(), nullable=True),
    sa.Column('spouse_health_notes', sa.Text(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('miscarriage_count >= 0', name=op.f('ck_medical_histories_miscarriages_non_negative')),
    sa.CheckConstraint('previous_children_count >= 0', name=op.f('ck_medical_histories_children_non_negative')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_medical_histories_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_medical_histories'))
    )
    op.create_table('pregnancies',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('lmp_date', sa.Date(), nullable=False),
    sa.Column('avg_cycle_length_days', sa.SmallInteger(), server_default='28', nullable=False),
    sa.Column('conception_type', sa.Enum('natural', 'assisted', name='conceptiontype', native_enum=False, length=40), nullable=False),
    sa.Column('estimated_due_date', sa.Date(), nullable=False),
    sa.Column('care_provider_type', sa.Enum('specialist', 'midwife', 'health_center', name='careprovidertype', native_enum=False, length=40), nullable=True),
    sa.Column('care_provider_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.Enum('active', 'delivered', 'ended', name='pregnancystatus', native_enum=False, length=40), server_default='active', nullable=False),
    sa.Column('ended_on', sa.Date(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("care_provider_type IN ('specialist', 'midwife', 'health_center')", name=op.f('ck_pregnancies_care_provider_type_valid')),
    sa.CheckConstraint("conception_type IN ('natural', 'assisted')", name=op.f('ck_pregnancies_conception_type_valid')),
    sa.CheckConstraint("status IN ('active', 'delivered', 'ended')", name=op.f('ck_pregnancies_status_valid')),
    sa.CheckConstraint('avg_cycle_length_days BETWEEN 20 AND 45', name=op.f('ck_pregnancies_cycle_length_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_pregnancies_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_pregnancies'))
    )
    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pregnancies_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_pregnancies_one_active_per_user', ['user_id'], unique=True, postgresql_where=sa.text("status = 'active'"))

    op.create_table('profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('national_code', sa.String(length=10), nullable=True),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('height_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('initial_weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('mother_blood_type', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', name='bloodtype', native_enum=False, length=40), nullable=True),
    sa.Column('father_blood_type', sa.Enum('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-', name='bloodtype', native_enum=False, length=40), nullable=True),
    sa.Column('reproductive_status', sa.Enum('trying_to_conceive', 'pregnant', 'postpartum', name='reproductivestatus', native_enum=False, length=40), nullable=True),
    sa.Column('join_goal', sa.Enum('pregnancy', 'fitness', 'rehabilitation', name='joingoal', native_enum=False, length=40), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("father_blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')", name=op.f('ck_profiles_father_blood_type_valid')),
    sa.CheckConstraint("join_goal IN ('pregnancy', 'fitness', 'rehabilitation')", name=op.f('ck_profiles_join_goal_valid')),
    sa.CheckConstraint("mother_blood_type IN ('A+', 'A-', 'B+', 'B-', 'AB+', 'AB-', 'O+', 'O-')", name=op.f('ck_profiles_mother_blood_type_valid')),
    sa.CheckConstraint("national_code ~ '^[0-9]{10}$'", name=op.f('ck_profiles_national_code_format')),
    sa.CheckConstraint("reproductive_status IN ('trying_to_conceive', 'pregnant', 'postpartum')", name=op.f('ck_profiles_reproductive_status_valid')),
    sa.CheckConstraint('height_cm BETWEEN 50 AND 250', name=op.f('ck_profiles_height_range')),
    sa.CheckConstraint('initial_weight_kg BETWEEN 20 AND 300', name=op.f('ck_profiles_weight_range')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_profiles')),
    sa.UniqueConstraint('national_code', name=op.f('uq_profiles_national_code'))
    )
    op.create_table('risk_tag_assignments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('tag', sa.Enum('needs_rhogam', 'thyroid', 'miscarriage_history', 'diabetes', 'hypertension', 'anemia', 'infectious_disease', 'other', name='risktag', native_enum=False, length=40), nullable=False),
    sa.Column('note', sa.String(length=255), nullable=True),
    sa.Column('added_by_id', sa.UUID(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("tag IN ('needs_rhogam', 'thyroid', 'miscarriage_history', 'diabetes', 'hypertension', 'anemia', 'infectious_disease', 'other')", name=op.f('ck_risk_tag_assignments_tag_valid')),
    sa.ForeignKeyConstraint(['added_by_id'], ['users.id'], name=op.f('fk_risk_tag_assignments_added_by_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_risk_tag_assignments_patient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_risk_tag_assignments')),
    sa.UniqueConstraint('patient_id', 'tag', name='uq_risk_tag_per_patient')
    )
    with op.batch_alter_table('risk_tag_assignments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_risk_tag_assignments_patient_id'), ['patient_id'], unique=False)

    op.create_table('staff_notes',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('author_id', sa.UUID(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['users.id'], name=op.f('fk_staff_notes_author_id_users')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_staff_notes_patient_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_staff_notes'))
    )
    with op.batch_alter_table('staff_notes', schema=None) as batch_op:
        batch_op.create_index('ix_staff_notes_patient_created_at', ['patient_id', 'created_at'], unique=False)

    op.create_table('user_sessions',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('refresh_token_hash', sa.String(length=255), nullable=False),
    sa.Column('ip_address', postgresql.INET(), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_sessions_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('refresh_token_hash', name=op.f('uq_user_sessions_refresh_token_hash'))
    )
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_sessions_user_id'), ['user_id'], unique=False)

    op.create_table('daily_logs',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_id', sa.UUID(), nullable=True),
    sa.Column('recorded_by_id', sa.UUID(), nullable=False),
    sa.Column('recorded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('has_spotting_or_bleeding', sa.Boolean(), nullable=True),
    sa.Column('systolic_bp', sa.SmallInteger(), nullable=True),
    sa.Column('diastolic_bp', sa.SmallInteger(), nullable=True),
    sa.Column('blood_glucose_mg_dl', sa.SmallInteger(), nullable=True),
    sa.Column('weight_kg', sa.Numeric(precision=5, scale=2), nullable=True),
    sa.Column('has_acid_reflux', sa.Boolean(), nullable=True),
    sa.Column('has_blurred_vision', sa.Boolean(), nullable=True),
    sa.Column('has_headache', sa.Boolean(), nullable=True),
    sa.Column('has_palpitations', sa.Boolean(), nullable=True),
    sa.Column('has_heartburn', sa.Boolean(), nullable=True),
    sa.Column('has_reduced_fetal_movement', sa.Boolean(), nullable=True),
    sa.Column('other_complaints', sa.Text(), nullable=True),
    sa.Column('is_red_alert', sa.Boolean(), sa.Computed('COALESCE(has_spotting_or_bleeding, false)', persisted=True), nullable=False),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('blood_glucose_mg_dl BETWEEN 20 AND 600', name=op.f('ck_daily_logs_glucose_range')),
    sa.CheckConstraint('diastolic_bp BETWEEN 30 AND 160', name=op.f('ck_daily_logs_diastolic_range')),
    sa.CheckConstraint('systolic_bp BETWEEN 50 AND 260', name=op.f('ck_daily_logs_systolic_range')),
    sa.CheckConstraint('weight_kg BETWEEN 20 AND 300', name=op.f('ck_daily_logs_weight_range')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_daily_logs_patient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], name=op.f('fk_daily_logs_pregnancy_id_pregnancies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['recorded_by_id'], ['users.id'], name=op.f('fk_daily_logs_recorded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_daily_logs'))
    )
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.create_index('ix_daily_logs_patient_recorded_at', ['patient_id', sa.literal_column('recorded_at DESC')], unique=False)
        batch_op.create_index(batch_op.f('ix_daily_logs_pregnancy_id'), ['pregnancy_id'], unique=False)
        batch_op.create_index('ix_daily_logs_red_alerts', ['patient_id'], unique=False, postgresql_where=sa.text('is_red_alert'))

    op.create_table('medical_documents',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('uploaded_by_id', sa.UUID(), nullable=False),
    sa.Column('pregnancy_id', sa.UUID(), nullable=True),
    sa.Column('document_type', sa.Enum('blood_test', 'urine_test', 'thyroid_test', 'ultrasound', 'screening', 'imaging', 'other', name='documenttype', native_enum=False, length=40), nullable=False),
    sa.Column('storage_key', sa.String(length=512), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('file_size_bytes', sa.BigInteger(), nullable=False),
    sa.Column('performed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fundal_height_cm', sa.Numeric(precision=4, scale=1), nullable=True),
    sa.Column('fetal_heart_rate_bpm', sa.SmallInteger(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("document_type IN ('blood_test', 'urine_test', 'thyroid_test', 'ultrasound', 'screening', 'imaging', 'other')", name=op.f('ck_medical_documents_document_type_valid')),
    sa.CheckConstraint('fetal_heart_rate_bpm BETWEEN 50 AND 250', name=op.f('ck_medical_documents_fetal_hr_range')),
    sa.CheckConstraint('file_size_bytes > 0', name=op.f('ck_medical_documents_file_size_positive')),
    sa.CheckConstraint('fundal_height_cm BETWEEN 5 AND 60', name=op.f('ck_medical_documents_fundal_height_range')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_medical_documents_patient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pregnancy_id'], ['pregnancies.id'], name=op.f('fk_medical_documents_pregnancy_id_pregnancies'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['uploaded_by_id'], ['users.id'], name=op.f('fk_medical_documents_uploaded_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_medical_documents')),
    sa.UniqueConstraint('storage_key', name=op.f('uq_medical_documents_storage_key'))
    )
    with op.batch_alter_table('medical_documents', schema=None) as batch_op:
        batch_op.create_index('ix_medical_documents_patient_performed_at', ['patient_id', 'performed_at'], unique=False)

    op.create_table('rehab_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('subcategory', sa.Enum('injury_correction', 'postpartum_recovery', 'performance_improvement', 'yoga_meditation', 'orthopedic_referral', name='rehabsubcategory', native_enum=False, length=40), nullable=False),
    sa.Column('pain_level', sa.SmallInteger(), nullable=False),
    sa.Column('had_related_surgery', sa.Boolean(), nullable=False),
    sa.Column('related_surgery_name', sa.String(length=255), nullable=True),
    sa.Column('uses_pain_medication', sa.Boolean(), nullable=False),
    sa.Column('injury_onset', sa.Enum('recent', 'one_to_six_months', 'chronic', name='injuryonset', native_enum=False, length=40), nullable=True),
    sa.Column('pain_type', sa.Enum('shooting', 'burning_tingling', 'dull_aching', name='paintype', native_enum=False, length=40), nullable=True),
    sa.Column('has_daily_movement_limitation', sa.Boolean(), nullable=True),
    sa.Column('time_since_delivery', sa.Enum('under_40_days', 'two_to_six_months', 'over_six_months', name='timesincedelivery', native_enum=False, length=40), nullable=True),
    sa.Column('has_pelvic_warning_signs', sa.Boolean(), nullable=True),
    sa.Column('has_diastasis_recti_or_stitch_pain', sa.Boolean(), nullable=True),
    sa.Column('training_goal', sa.Enum('stress_reduction', 'flexibility', 'posture_correction', 'chronic_stiffness_relief', name='traininggoal', native_enum=False, length=40), nullable=True),
    sa.Column('fitness_level', sa.Enum('inactive', 'beginner', 'professional', name='fitnesslevel', native_enum=False, length=40), nullable=True),
    sa.Column('has_recurrent_muscle_spasms', sa.Boolean(), nullable=True),
    sa.Column('referral_reason', sa.Enum('severe_joint_pain', 'injury_fracture', 'spine_checkup', name='orthopedicreferralreason', native_enum=False, length=40), nullable=True),
    sa.Column('imaging_document_id', sa.UUID(), nullable=True),
    sa.Column('specialist_visit_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False),
    sa.Column('specialist_visit_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("fitness_level IN ('inactive', 'beginner', 'professional')", name=op.f('ck_rehab_profiles_fitness_level_valid')),
    sa.CheckConstraint("injury_onset IN ('recent', 'one_to_six_months', 'chronic')", name=op.f('ck_rehab_profiles_injury_onset_valid')),
    sa.CheckConstraint("pain_type IN ('shooting', 'burning_tingling', 'dull_aching')", name=op.f('ck_rehab_profiles_pain_type_valid')),
    sa.CheckConstraint("referral_reason IN ('severe_joint_pain', 'injury_fracture', 'spine_checkup')", name=op.f('ck_rehab_profiles_referral_reason_valid')),
    sa.CheckConstraint("subcategory IN ('injury_correction', 'postpartum_recovery', 'performance_improvement', 'yoga_meditation', 'orthopedic_referral')", name=op.f('ck_rehab_profiles_subcategory_valid')),
    sa.CheckConstraint("time_since_delivery IN ('under_40_days', 'two_to_six_months', 'over_six_months')", name=op.f('ck_rehab_profiles_time_since_delivery_valid')),
    sa.CheckConstraint("training_goal IN ('stress_reduction', 'flexibility', 'posture_correction', 'chronic_stiffness_relief')", name=op.f('ck_rehab_profiles_training_goal_valid')),
    sa.CheckConstraint('had_related_surgery IS NOT TRUE OR related_surgery_name IS NOT NULL', name=op.f('ck_rehab_profiles_surgery_name_required')),
    sa.CheckConstraint('pain_level BETWEEN 1 AND 10', name=op.f('ck_rehab_profiles_pain_level_range')),
    sa.ForeignKeyConstraint(['imaging_document_id'], ['medical_documents.id'], name=op.f('fk_rehab_profiles_imaging_document_id_medical_documents'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_rehab_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_rehab_profiles'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rehab_profiles')
    with op.batch_alter_table('medical_documents', schema=None) as batch_op:
        batch_op.drop_index('ix_medical_documents_patient_performed_at')

    op.drop_table('medical_documents')
    with op.batch_alter_table('daily_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_daily_logs_red_alerts', postgresql_where=sa.text('is_red_alert'))
        batch_op.drop_index(batch_op.f('ix_daily_logs_pregnancy_id'))
        batch_op.drop_index('ix_daily_logs_patient_recorded_at')

    op.drop_table('daily_logs')
    with op.batch_alter_table('user_sessions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_sessions_user_id'))

    op.drop_table('user_sessions')
    with op.batch_alter_table('staff_notes', schema=None) as batch_op:
        batch_op.drop_index('ix_staff_notes_patient_created_at')

    op.drop_table('staff_notes')
    with op.batch_alter_table('risk_tag_assignments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_risk_tag_assignments_patient_id'))

    op.drop_table('risk_tag_assignments')
    op.drop_table('profiles')
    with op.batch_alter_table('pregnancies', schema=None) as batch_op:
        batch_op.drop_index('uq_pregnancies_one_active_per_user', postgresql_where=sa.text("status = 'active'"))
        batch_op.drop_index(batch_op.f('ix_pregnancies_user_id'))

    op.drop_table('pregnancies')
    op.drop_table('medical_histories')
    op.drop_table('fitness_profiles')
    with op.batch_alter_table('care_approvals', schema=None) as batch_op:
        batch_op.drop_index('uq_care_approvals_one_active_per_scope', postgresql_where=sa.text('revoked_at IS NULL'))

    op.drop_table('care_approvals')
    op.drop_table('users')
    with op.batch_alter_table('otp_codes', schema=None) as batch_op:
        batch_op.drop_index('ix_otp_codes_mobile_created_at')

    op.drop_table('otp_codes')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_logs_patient_created_at')
        batch_op.drop_index(batch_op.f('ix_audit_logs_event_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index('ix_audit_logs_actor_created_at')

    op.drop_table('audit_logs')
    # ### end Alembic commands ###
