"""Phase 1 features: staff profiles, midwife choice, alerts, document files,
partner links, the fitness specialist visit and new audit event types.

Revision ID: f52a06369cf8
Revises: a467d701ee11
Create Date: 2026-10-01 09:05:19.228766

"""
from alembic import op
import sqlalchemy as sa


# Audit event types are stored as VARCHAR with a CHECK constraint; listed here so this
# migration keeps meaning the same thing if the enum changes later.
OLD_AUDIT_EVENTS = (
    "profile_created", "record_viewed", "record_updated", "access_denied", "login_succeeded",
    "login_failed", "document_uploaded", "approval_granted", "approval_revoked",
)
NEW_AUDIT_EVENTS = OLD_AUDIT_EVENTS + (
    "record_created", "staff_account_created", "staff_account_updated", "midwife_chosen",
    "alert_seen", "partner_link_created", "partner_link_revoked", "partner_link_viewed",
)


def _audit_event_check(values) -> None:
    op.drop_constraint(op.f("ck_audit_logs_event_type_valid"), "audit_logs", type_="check")
    allowed = ", ".join(f"'{v}'" for v in values)
    op.create_check_constraint(
        op.f("ck_audit_logs_event_type_valid"), "audit_logs", f"event_type IN ({allowed})"
    )


# revision identifiers, used by Alembic.
revision = 'f52a06369cf8'
down_revision = 'a467d701ee11'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('care_assignments',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('staff_id', sa.UUID(), nullable=False),
    sa.Column('care_role', sa.Enum('midwife', 'doctor', name='carerole', native_enum=False, length=40), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("care_role IN ('midwife', 'doctor')", name=op.f('ck_care_assignments_care_role_valid')),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_care_assignments_patient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['staff_id'], ['users.id'], name=op.f('fk_care_assignments_staff_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_care_assignments'))
    )
    with op.batch_alter_table('care_assignments', schema=None) as batch_op:
        batch_op.create_index('ix_care_assignments_active_staff', ['staff_id', 'care_role'], unique=False, postgresql_where=sa.text('ended_at IS NULL'))
        batch_op.create_index('uq_care_assignments_one_active_per_role', ['patient_id', 'care_role'], unique=True, postgresql_where=sa.text('ended_at IS NULL'))

    op.create_table('partner_links',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_partner_links_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_partner_links'))
    )
    with op.batch_alter_table('partner_links', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_links_user_id'), ['user_id'], unique=False)
        batch_op.create_index('uq_partner_links_one_active_per_user', ['user_id'], unique=True, postgresql_where=sa.text('revoked_at IS NULL'))

    op.create_table('staff_profiles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('is_listed', sa.Boolean(), server_default=sa.text('true'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_staff_profiles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_staff_profiles'))
    )
    op.create_table('alerts',
    sa.Column('patient_id', sa.UUID(), nullable=False),
    sa.Column('kind', sa.Enum('bleeding', name='alertkind', native_enum=False, length=40), nullable=False),
    sa.Column('daily_log_id', sa.UUID(), nullable=True),
    sa.Column('seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seen_by_id', sa.UUID(), nullable=True),
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("kind IN ('bleeding')", name=op.f('ck_alerts_kind_valid')),
    sa.ForeignKeyConstraint(['daily_log_id'], ['daily_logs.id'], name=op.f('fk_alerts_daily_log_id_daily_logs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['patient_id'], ['users.id'], name=op.f('fk_alerts_patient_id_users'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['seen_by_id'], ['users.id'], name=op.f('fk_alerts_seen_by_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alerts'))
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_open', ['patient_id'], unique=False, postgresql_where=sa.text('seen_at IS NULL'))

    op.create_table('document_files',
    sa.Column('document_id', sa.UUID(), nullable=False),
    sa.Column('content', sa.LargeBinary(), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['medical_documents.id'], name=op.f('fk_document_files_document_id_medical_documents'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('document_id', name=op.f('pk_document_files'))
    )
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('specialist_visit_completed', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('specialist_visit_at', sa.DateTime(timezone=True), nullable=True))

    # ### end Alembic commands ###
    _audit_event_check(NEW_AUDIT_EVENTS)


def downgrade():
    # Fails if the log already holds the new event types: audit rows are never deleted.
    _audit_event_check(OLD_AUDIT_EVENTS)
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('fitness_profiles', schema=None) as batch_op:
        batch_op.drop_column('specialist_visit_at')
        batch_op.drop_column('specialist_visit_completed')

    op.drop_table('document_files')
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.drop_index('ix_alerts_open', postgresql_where=sa.text('seen_at IS NULL'))

    op.drop_table('alerts')
    op.drop_table('staff_profiles')
    with op.batch_alter_table('partner_links', schema=None) as batch_op:
        batch_op.drop_index('uq_partner_links_one_active_per_user', postgresql_where=sa.text('revoked_at IS NULL'))
        batch_op.drop_index(batch_op.f('ix_partner_links_user_id'))

    op.drop_table('partner_links')
    with op.batch_alter_table('care_assignments', schema=None) as batch_op:
        batch_op.drop_index('uq_care_assignments_one_active_per_role', postgresql_where=sa.text('ended_at IS NULL'))
        batch_op.drop_index('ix_care_assignments_active_staff', postgresql_where=sa.text('ended_at IS NULL'))

    op.drop_table('care_assignments')
    # ### end Alembic commands ###
